"""
Exports a report of queries and their corresponding pages from a Google 
Search Console property.
Refactored for modular GSC Exporter.
"""
import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import pandas as pd
from datetime import datetime, date, timedelta
from core.naming import get_output_dir, get_filename_slug
from core.cache import fetch_with_cache

def generate_accordion_html(df, primary_dim, secondary_dim, report_limit, sub_table_limit):
    """Generates the accordion HTML for the report."""
    accordion_id = f"accordion-{primary_dim}"
    html_parts = [f'<div class="accordion mt-3" id="{accordion_id}">']

    primary_totals = df.groupby(primary_dim).agg(
        total_clicks=('clicks', 'sum'),
        total_impressions=('impressions', 'sum')
    ).sort_values(by='total_clicks', ascending=False).head(report_limit).reset_index()

    for i, row in primary_totals.iterrows():
        primary_val = row[primary_dim]
        
        sub_df = df[df[primary_dim] == primary_val].head(sub_table_limit).copy()
        
        # Format for table display
        if secondary_dim == 'page':
            sub_df['page'] = sub_df['page'].apply(lambda x: f'<a href="{x}" target="_blank" class="text-break">{x}</a>')

        sub_df['ctr'] = sub_df['ctr'].apply(lambda x: f"{x:.2%}")
        sub_df['position'] = sub_df['position'].apply(lambda x: f"{x:.2f}")

        table_html = sub_df[[secondary_dim, 'clicks', 'impressions', 'ctr', 'position']].to_html(
            classes="table table-sm table-striped", index=False, border=0, escape=False
        )

        html_parts.append(f"""
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{primary_dim}-{i}">
                    <div class="d-flex w-100 align-items-center">
                        <span class="text-truncate" style="max-width: 70%;">{primary_val}</span>
                        <div class="ms-auto">
                            <span class="badge bg-primary me-2">Clicks: {row['total_clicks']:,}</span>
                            <span class="badge bg-secondary">Impr: {row['total_impressions']:,}</span>
                        </div>
                    </div>
                </button>
            </h2>
            <div id="collapse-{primary_dim}-{i}" class="accordion-collapse collapse" data-bs-parent="#{accordion_id}">
                <div class="accordion-body">
                    {table_html}
                </div>
            </div>
        </div>
        """)
    
    html_parts.append('</div>')
    return "".join(html_parts)

def create_html_report(data_df, site_url, start_date, end_date, report_limit, sub_table_limit):
    """Generates the interactive HTML report."""
    
    html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Google Organic Pages & Queries Report: {site_url}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        body {{ padding: 2rem; background-color: #f8f9fa; }}
        h1 {{ border-bottom: 2px solid #dee2e6; padding-bottom: .5rem; }}
        .table td {{ word-wrap: break-word; max-width: 500px; }}
        .text-break {{ word-break: break-all !important; }}
        .accordion-button:not(.collapsed) {{ background-color: #e7f1ff; }}
    </style>
</head>
<body>
    <div class="container-fluid">
        <h1>Google Organic Pages & Queries Report</h1>
        <p class="lead">{site_url} ({start_date} to {end_date})</p>

        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <button class="nav-link active" id="queries-tab" data-bs-toggle="tab" data-bs-target="#queries" type="button">Queries to Pages</button>
            </li>
            <li class="nav-item">
                <button class="nav-link" id="pages-tab" data-bs-toggle="tab" data-bs-target="#pages" type="button">Pages to Queries</button>
            </li>
        </ul>

        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="queries" role="tabpanel">
                {generate_accordion_html(data_df, 'query', 'page', report_limit, sub_table_limit)}
            </div>
            <div class="tab-pane fade" id="pages" role="tabpanel">
                {generate_accordion_html(data_df, 'page', 'query', report_limit, sub_table_limit)}
            </div>
        </div>
    </div>
    <footer class="mt-5 text-center text-muted">
        <p>Generated by <a href="https://github.com/liamdelahunty/gsc-exporter" target="_blank">gsc-exporter</a></p>
    </footer>
</body>
</html>
    """
    return html_content

def run_report(service, site_url, start_date=None, end_date=None, report_limit=250, sub_table_limit=100):
    """Executes the Pages & Queries Detailed report."""
    print(f"Running GSC Pages & Queries Detailed for {site_url}...")
    
    # 1. Date Range
    if not start_date or not end_date:
        today = date.today()
        end_date_dt = today.replace(day=1) - timedelta(days=1)
        start_date_dt = end_date_dt.replace(day=1)
        start_date = start_date_dt.strftime('%Y-%m-%d')
        end_date = end_date_dt.strftime('%Y-%m-%d')

    # 2. Fetch Data
    # Dimensions: query, page
    df = fetch_with_cache(service, site_url, start_date, end_date, ['query', 'page'])
    
    if df.empty:
        print("No data found.")
        return None

    # 3. Output Paths
    output_dir = get_output_dir(site_url)
    os.makedirs(output_dir, exist_ok=True)
    slug = get_filename_slug(site_url)
    
    file_prefix = f"gsc-pages-queries-{slug}-{start_date}-to-{end_date}"
    csv_path = os.path.join(output_dir, f"{file_prefix}.csv")
    html_path = os.path.join(output_dir, f"{file_prefix}.html")

    # 4. Save CSV
    df.to_csv(csv_path, index=False)
    
    # 5. Generate HTML
    html_content = create_html_report(df, site_url, start_date, end_date, report_limit, sub_table_limit)
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
        
    print(f"Report completed: {html_path}")
    return html_path

if __name__ == '__main__':
    import argparse
    from core.client import get_gsc_service
    
    parser = argparse.ArgumentParser(description='Export GSC pages and queries.')
    parser.add_argument('site_url', help='The URL of the site.')
    parser.add_argument('--start-date', help='Start date.')
    parser.add_argument('--end-date', help='End date.')
    parser.add_argument('--report-limit', type=int, default=250)
    parser.add_argument('--sub-table-limit', type=int, default=100)
    
    args = parser.parse_args()
    service = get_gsc_service()
    if service:
        run_report(service, args.site_url, args.start_date, args.end_date, args.report_limit, args.sub_table_limit)
